### ISSUE TITLE
Add error handling to the JSON parsing in import

### ISSUE THREAD

**Issue by LaChapeliere** [CRANE-toolbox/analysis-pipelines#25]
When providing an array-wrapped JSON, for example, the code crashes

`[{"id": 112454, "text": "bobeagle", "created_at":"date", "lang":"en"}, {"id": 112454, "text": "bobeagle", "created_at": "date2"}]`

`emma@cobra-compute:~$ crane-import --source-folder inputtests --output-name test4.csv
Found the following files
[PurePosixPath('inputtests/inputestJSON'), PurePosixPath('inputtests/inputtest.json')]
Processing file inputtests/inputestJSON
Traceback (most recent call last):
  File "/home/emma/.local/bin/crane-import", line 8, in <module>
    sys.exit(main())
  File "/home/emma/.local/lib/python3.6/site-packages/cranetoolbox/importTools/__main__.py", line 30, in main
    line_count, failure_count = process_files(file_list, opts, path.join(args.output_folder, args.output_name))
  File "/home/emma/.local/lib/python3.6/site-packages/cranetoolbox/importTools/transform.py", line 53, in process_files
    lines_written, failures = write_tweets_by_chunk(f, csv_output_path, opts)
  File "/home/emma/.local/lib/python3.6/site-packages/cranetoolbox/importTools/transform.py", line 85, in write_tweets_by_chunk
    filtered_chunk, failure_count = filter_lighten_chunk(chunk, opts)
  File "/home/emma/.local/lib/python3.6/site-packages/cranetoolbox/importTools/transform.py", line 111, in filter_lighten_chunk
    if matches_language_filter(tweet, opts) and not is_retweet(tweet):
  File "/home/emma/.local/lib/python3.6/site-packages/cranetoolbox/importTools/transform.py", line 170, in matches_language_filter
    language = tweet.get("lang", None)
AttributeError: 'list' object has no attribute 'get'`

**Comment by LaChapeliere** [comment]
Also crashes if a field supposed to be a dict is actually a str, for example.
`{"id": 112454, "text": "bobeagle", "created_at":"date", "lang":"en", "truncated": true, "extended_tweet": "blob"}` where extended_tweet should be a dict

**Comment by jd7h** [comment]
I can take a look at this. :)

**Comment by jd7h** [comment]
It would be helpful if you could provide a description of the behaviour that you DO want, in case the input is not in the format cranetoolbox expects.

**Comment by LaChapeliere** [comment]
Thank you!
Badly formatted lines are supposed to be not included in the output and counted in the `failure_count` variable. The same behaviour as lines that are properly formatted but don't have the required fields.

**Comment by LaChapeliere** [comment]
@all-contributors please add @jd7h for code
